# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fab37a3622bfa5c5e8622db112dad27519a10990e775b7bc4068ed41f6ae26ce493c1d6d4d2b610009cbe0e33455583cd5b79aa00d4d21583ac3f35a83dccec

test:
  secret_key_base: c3c985535dbc293d94977c18635e1240b4789f21efa40a7b278d9e7d211f549a8d13c9559f15dcb233ea2994b8f2f54b96a5d59ad1adbe444f4fc11cc5e1c805

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
